# Generated by Django 5.2.8 on 2025-11-08 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_profile_save_saves_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='worlds',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
