# Generated by Django 5.2.8 on 2025-11-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_worlds_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saves',
            old_name='world_id',
            new_name='world',
        ),
        migrations.RenameField(
            model_name='worlds',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
