# Generated by Django 5.2.8 on 2025-11-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_world_id_saves_world_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worlds',
            old_name='challenges',
            new_name='level_data',
        ),
        migrations.RemoveField(
            model_name='worlds',
            name='collection_cards',
        ),
        migrations.RemoveField(
            model_name='worlds',
            name='world_cards',
        ),
    ]
