# Generated by Django 5.2.8 on 2025-11-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_challenges_worlds_level_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isJatekmeste',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
