# Generated by Django 5.2.8 on 2025-11-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile_isjatekmeste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='isJatekmeste',
            new_name='isJatekmester',
        ),
    ]
